version: "3.9"

services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    
    # remove this when using Jenkins pipeline
    # volumes:
    #   - .:/app
    
    command: sh -lc "echo '=== CONTAINER DEBUG ===' && pwd && echo '=== END DEBUG ===' && npm install && npm test"
    tty: true
    stdin_open: true
