version: "3.9"

services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ${JENKINS_WORKSPACE:-.}:/app
    command: sh -lc "echo '=== CONTAINER DEBUG ===' && pwd && ls -la && echo '=== END DEBUG ===' && npm install && npm test"
    # If you need interactive debugging:
    tty: true
    stdin_open: true
