version: "3.9"

services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    command: sh -lc "echo '=== CONTAINER DEBUG ===' && cd qa-adv-4-dockerbasic && pwd && ls -la && echo '=== END DEBUG ===' && npm install && npm test"
    tty: true
    stdin_open: true
